### ISSUE TITLE
Background-grid/debug doesnt work

### ISSUE THREAD

**Issue by the-Dean** [at-import/Singularity#214] opened 2015-07-10 15:28 UTC
I get a bus error: 10, when I have both of these in my scss file. Any help on getting this to work would be great. Below is my scss:

```
@include add-grid(12);
@include add-gutter(1/3);
@include sgs-change('debug',true);

.container {
    @include background-grid;
}
```

I can create grids, I just can't get the background grid to show up...

**Comment by Snugug** [comment] 2016-02-21 15:37
Duplicate of #211

**Closed as completed by Snugug** 2016-02-21 15:37 UTC
